export const mockedCodeSystems = [
  {
    id: "1",
    name: "Code1",
    title: "Code 1",
    version: "1.0",
    lastUpdatedUpstream: new Date(1999, 10, 1).toString(),
    lastUpdated: Date.now().toString(),
  },
  {
    id: "2",
    name: "Code1",
    title: "Code 1",
    version: "2.0",
    lastUpdatedUpstream: new Date(2000, 10, 1).toString(),
    lastUpdated: Date.now().toString(),
  },
  {
    id: "3",
    name: "Code2",
    title: "Code 2",
    version: "1.0",
    lastUpdatedUpstream: new Date(1999, 10, 1).toString(),
    lastUpdated: Date.now().toString(),
  },
  {
    id: "4",
    name: "Code2",
    title: "Code 2",
    version: "2.0",
    lastUpdatedUpstream: new Date(2000, 10, 1).toString(),
    lastUpdated: Date.now().toString(),
  },
  {
    id: "5",
    name: "code3",
    title: "code 3",
    version: "1.0",
    lastUpdatedUpstream: new Date(1999, 10, 1).toString(),
    lastUpdated: Date.now().toString(),
  },
  {
    id: "6",
    name: "code3",
    title: "code 3",
    version: "2.0",
    lastUpdatedUpstream: new Date(2001, 10, 1).toString(),
    lastUpdated: Date.now().toString(),
  },
];
