export const mockedCodeSystems = [
  {
    id: "1",
    name: "System1",
    title: "System 1",
    version: "1.0",
    lastUpdatedUpstream: new Date(1999, 10, 1).toString(),
    lastUpdated: Date.now().toString(),
  },
  {
    id: "2",
    name: "System1",
    title: "System 1",
    version: "2.0",
    lastUpdatedUpstream: new Date(2000, 10, 1).toString(),
    lastUpdated: Date.now().toString(),
  },
  {
    id: "3",
    name: "System2",
    title: "System 2",
    version: "1.0",
    lastUpdatedUpstream: new Date(1999, 10, 1).toString(),
    lastUpdated: Date.now().toString(),
  },
  {
    id: "4",
    name: "System2",
    title: "System 2",
    version: "2.0",
    lastUpdatedUpstream: new Date(2000, 10, 1).toString(),
    lastUpdated: Date.now().toString(),
  },
  {
    id: "5",
    name: "System3",
    title: "System 3",
    version: "1.0",
    lastUpdatedUpstream: new Date(1999, 10, 1).toString(),
    lastUpdated: Date.now().toString(),
  },
  {
    id: "6",
    name: "System3",
    title: "System 3",
    version: "2.0",
    lastUpdatedUpstream: new Date(2001, 10, 1).toString(),
    lastUpdated: Date.now().toString(),
  },
];
