export const mockCqlLibraries = [
  {
    id: "12",
    cqlLibraryName: "Test12",
    version: "2.2.000",
    librarySet: { owner: "John", librarySetId: "10-12" },
    draft: false,
    alias: "Test",
    cql: "Test cql 12",
    librarySetId: "10-12",
    owner: "John",
  },
  {
    id: "11",
    cqlLibraryName: "Test11",
    version: "2.1.000",
    librarySet: { owner: "Jane", librarySetId: "10-13" },
    draft: false,
    cql: "Test cql 11",
    librarySetId: "10-12",
    owner: "Jane",
  },
  {
    id: "10",
    cqlLibraryName: "Test10",
    version: "2.0.000",
    librarySet: { owner: "Jane", librarySetId: "10-13" },
    draft: false,
    cql: "Test cql 10",
    librarySetId: "10-12",
    owner: "Jane",
  },
  {
    id: "9",
    cqlLibraryName: "Test9",
    version: "1.9.000",
    librarySet: { owner: "John", librarySetId: "8-9" },
    draft: false,
    librarySetId: "8-9",
    owner: "John",
  },
  {
    id: "8",
    cqlLibraryName: "Test8",
    version: "1.8.000",
    librarySet: { owner: "John", librarySetId: "8-9" },
    draft: false,
    librarySetId: "8-9",
    owner: "John",
  },
  {
    id: "7",
    cqlLibraryName: "Test7",
    version: "1.7.000",
    librarySet: { owner: "Paul", librarySetId: "7" },
    draft: false,
    librarySetId: "7",
    owner: "Paul",
  },
  {
    id: "6",
    cqlLibraryName: "Test6",
    version: "1.6.000",
    librarySet: { owner: "Paul", librarySetId: "6" },
    draft: false,
    librarySetId: "6",
    owner: "Paul",
  },
  {
    id: "5",
    cqlLibraryName: "Test5",
    version: "1.5.000",
    librarySet: { owner: "Paul", librarySetId: "5" },
    draft: false,
    librarySetId: "5",
    owner: "Paul",
  },
  {
    id: "4",
    cqlLibraryName: "Test4",
    version: "1.4.000",
    librarySet: { owner: "Paul", librarySetId: "4" },
    draft: false,
    librarySetId: "4",
    owner: "Paul",
  },
  {
    id: "3",
    cqlLibraryName: "Test3",
    version: "1.3.000",
    librarySet: { owner: "Paul", librarySetId: "3" },
    draft: false,
    librarySetId: "3",
    owner: "Paul",
  },
  {
    id: "2",
    cqlLibraryName: "Test2",
    version: "1.2.000",
    librarySet: { owner: "Paul", librarySetId: "2" },
    draft: false,
    librarySetId: "2",
    owner: "Paul",
  },
  {
    id: "1",
    cqlLibraryName: "Test1",
    version: "1.1.000",
    librarySet: { owner: "Paul", librarySetId: "1" },
    draft: false,
    librarySetId: "1",
    owner: "Paul",
  },
];
