export const mockCqlLibraries = [
  {
    id: "12",
    cqlLibraryName: "Test_12",
    version: "2.2.000",
    librarySet: { owner: "John" },
    draft: false,
  },
  {
    id: "11",
    cqlLibraryName: "Test_11",
    version: "2.1.000",
    librarySet: { owner: "Jane" },
    draft: false,
  },
  {
    id: "10",
    cqlLibraryName: "Test_10",
    version: "2.0.000",
    librarySet: { owner: "Jane" },
    draft: false,
  },
  {
    id: "9",
    cqlLibraryName: "Test_9",
    version: "1.9.000",
    librarySet: { owner: "John" },
    draft: false,
  },
  {
    id: "8",
    cqlLibraryName: "Test_8",
    version: "1.8.000",
    librarySet: { owner: "John" },
    draft: false,
  },
  {
    id: "7",
    cqlLibraryName: "Test_7",
    version: "1.7.000",
    librarySet: { owner: "Paul" },
    draft: false,
  },
  {
    id: "6",
    cqlLibraryName: "Test_6",
    version: "1.6.000",
    librarySet: { owner: "Paul" },
    draft: false,
  },
  {
    id: "5",
    cqlLibraryName: "Test_5",
    version: "1.5.000",
    librarySet: { owner: "Paul" },
    draft: false,
  },
  {
    id: "4",
    cqlLibraryName: "Test_4",
    version: "1.4.000",
    librarySet: { owner: "Paul" },
    draft: false,
  },
  {
    id: "3",
    cqlLibraryName: "Test_3",
    version: "1.3.000",
    librarySet: { owner: "Paul" },
    draft: false,
  },
  {
    id: "2",
    cqlLibraryName: "Test_2",
    version: "1.2.000",
    librarySet: { owner: "Paul" },
    draft: false,
  },
  {
    id: "1",
    cqlLibraryName: "Test_1",
    version: "1.1.000",
    librarySet: { owner: "Paul" },
    draft: false,
  },
];
