export const cqlBuilderLookupsTypes = {
  parameters: ["Measurement Period", "Global.Measurement Period"],
  definitions: [
    "SDE",
    "Global.Inpatient Encounter",
    "Index Depression Assessment",
    "SDE Sex",
    "Initial Population",
    "Stratification 2",
    "Has Palliative Care in the Measure Assessment Period",
    "SDE Denominator",
    "SDE Race",
    "Denominator Identification Period",
    "Has Mental Health Disorder Diagnoses",
    "Has Hospice Services in the Measure Assessment Period",
    "Measure Assessment Period",
    "Depression Assessments Greater than 9",
    "Depression Encounter",
    "Global.ED Encounter",
    "Denominator Exclusions",
    "Patient Expired",
    "SDE Ethnicity",
    "SDE Payer",
    "Numerator",
    "Depression Diagnoses",
    "Stratification 1",
  ],
  functions: [
    "Global.Latest()",
    "Global.HospitalizationLengthofStay()",
    "Global.HospitalizationLocations()",
    "Global.ToDateInterval()",
    "Global.HospitalDepartureTime()",
    "Global.Hospitalization()",
    "Global.EmergencyDepartmentArrivalTime()",
    "Global.HospitalizationWithObservationLengthofStay()",
    "Global.LengthInDays()",
    "Global.NormalizeInterval()",
    "Global.HasStart()",
    "Global.HospitalArrivalTime()",
    "Global.HasEnd()",
    "Global.HospitalizationWithObservation()",
    "Global.HospitalAdmissionTime()",
    "Global.FirstInpatientIntensiveCareUnit()",
    "Global.Earliest()",
    "Global.HospitalizationWithObservationAndOutpatientSurgeryService()",
    "Global.EarliestOf()",
    "Global.LatestOf()",
    "Global.HospitalDischargeTime()",
  ],
  fluentFunctions: [],
};
