import type * as monacoTypes from "monaco-editor";

export const CQL_LANGUAGE_ID = "cql";

export function registerCqlLanguage(monaco: typeof monacoTypes) {
  // Only register once
  if (
    monaco.languages.getLanguages().some((lang) => lang.id === CQL_LANGUAGE_ID)
  ) {
    return;
  }

  monaco.languages.register({ id: CQL_LANGUAGE_ID });

  monaco.languages.setMonarchTokensProvider(CQL_LANGUAGE_ID, {
    ignoreCase: false,
    defaultToken: "identifier",

    keywords: [
      "after",
      "aggregate",
      "all",
      "and",
      "as",
      "asc",
      "ascending",
      "before",
      "begins",
      "begun",
      "between",
      "Boolean",
      "by",
      "called",
      "case",
      "cast",
      "Choice",
      "Code",
      "codesystem",
      "codesystems",
      "collapse",
      "Concept",
      "contains",
      "context",
      "convert",
      "date",
      "Date",
      "DateTime",
      "day",
      "days",
      "Decimal",
      "default",
      "define",
      "desc",
      "descending",
      "difference",
      "display",
      "distinct",
      "div",
      "duration",
      "during",
      "else",
      "end",
      "ends",
      "except",
      "exists",
      "expand",
      "false",
      "flatten",
      "from",
      "function",
      "hour",
      "hours",
      "if",
      "implies",
      "in",
      "include",
      "included",
      "includes",
      "Integer",
      "intersect",
      "Interval",
      "is",
      "less",
      "let",
      "library",
      "List",
      "maximum",
      "meets",
      "millisecond",
      "milliseconds",
      "minimum",
      "minute",
      "minutes",
      "mod",
      "month",
      "months",
      "more",
      "not",
      "null",
      "occurs",
      "of",
      "on",
      "or",
      "overlaps",
      "parameter",
      "per",
      "predecessor",
      "private",
      "properly",
      "public",
      "QDM",
      "Quantity",
      "Ratio",
      "return",
      "same",
      "second",
      "seconds",
      "singleton",
      "sort",
      "start",
      "starts",
      "String",
      "successor",
      "such",
      "Sum",
      "that",
      "than",
      "then",
      "Time",
      "time",
      "timezone",
      "timezoneoffset",
      "to",
      "true",
      "Tuple",
      "union",
      "using",
      "valueset",
      "version",
      "week",
      "weeks",
      "when",
      "where",
      "width",
      "with",
      "within",
      "without",
      "xor",
      "year",
      "years",
    ],

    builtinFunctions: [
      "Abs",
      "AgeInDays",
      "AgeInDaysAt",
      "AgeInHours",
      "AgeInHoursAt",
      "AgeInMinutes",
      "AgeInMinutesAt",
      "AgeInMonths",
      "AgeInMonthsAt",
      "AgeInSeconds",
      "AgeInSecondsAt",
      "AgeInWeeks",
      "AgeInWeeksAt",
      "AgeInYears",
      "AgeInYearsAt",
      "AllTrue",
      "AnyTrue",
      "Avg",
      "CalculateAgeInDays",
      "CalculateAgeInDaysAt",
      "CalculateAgeInHours",
      "CalculateAgeInHoursAt",
      "CalculateAgeInMinutes",
      "CalculateAgeInMinutesAt",
      "CalculateAgeInMonths",
      "CalculateAgeInMonthsAt",
      "CalculateAgeInSeconds",
      "CalculateAgeInSecondsAt",
      "CalculateAgeInWeeks",
      "CalculateAgeInWeeksAt",
      "CalculateAgeInYears",
      "CalculateAgeInYearsAt",
      "Ceiling",
      "Coalesce",
      "Count",
      "Exp",
      "First",
      "Floor",
      "GeometricMean",
      "HighBoundary",
      "IndexOf",
      "Last",
      "Length",
      "Ln",
      "Log",
      "LowBoundary",
      "Lower",
      "Matches",
      "Max",
      "Median",
      "Min",
      "Mode",
      "Now",
      "PopulationStdDev",
      "PopulationVariance",
      "Precision",
      "Product",
      "Round",
      "Size",
      "Skip",
      "Split",
      "SplitOnMatches",
      "StartsWith",
      "StdDev",
      "Substring",
      "Tail",
      "Take",
      "TimeOfDay",
      "ToBoolean",
      "ToDate",
      "ToDateTime",
      "ToDecimal",
      "ToInteger",
      "ToQuantity",
      "ToString",
      "ToTime",
      "Today",
      "Truncate",
      "Upper",
      "Variance",
    ],

    builtinConstants: [
      "Patient",
      "activeDatetime",
      "admissionSource",
      "anatomicalLocationSite",
      "authorDatetime",
      "birthDatetime",
      "category",
      "cause",
      "code",
      "components",
      "daysSupplied",
      "denominator",
      "diagnoses",
      "dischargeDisposition",
      "dispenser",
      "dosage",
      "expiredDatetime",
      "facilityLocation",
      "facilityLocations",
      "frequency",
      "high",
      "id",
      "identifier",
      "incisionDatetime",
      "lengthOfStay",
      "linkedPatientId",
      "locationPeriod",
      "low",
      "medium",
      "method",
      "namingSystem",
      "negationRationale",
      "numerator",
      "participationPeriod",
      "patientId",
      "performer",
      "presentOnAdmissionIndicator",
      "prevalencePeriod",
      "priority",
      "prescriber",
      "qualification",
      "rank",
      "reason",
      "recipient",
      "receivedDatetime",
      "recorder",
      "referenceRange",
      "refills",
      "relatedTo",
      "relationship",
      "relevantDatetime",
      "relevantPeriod",
      "result",
      "resultDatetime",
      "requester",
      "role",
      "route",
      "sender",
      "specialty",
      "statusDate",
      "sentDatetime",
      "setting",
      "severity",
      "status",
      "supply",
      "targetOutcome",
      "type",
      "unit",
      "value",
      "participant",
    ],

    operators: [
      "+",
      "-",
      "/",
      "*",
      "%",
      "<",
      ">",
      "<=",
      ">=",
      "=",
      "!=",
      "<>",
      "~",
      "!~",
    ],

    symbols: /[=><!~?:&|+\-*\/\^%]+/,

    tokenizer: {
      root: [
        // Line comments
        [/\/\/.*$/, "comment"],

        // Block comments
        [/\/\*/, "comment", "@comment"],

        // Strings
        [/"([^"\\]|\\.)*$/, "string.invalid"],
        [/"/, "string", "@doubleString"],
        [/'([^'\\]|\\.)*$/, "string.invalid"],
        [/'/, "string", "@singleString"],

        // Numbers
        [/[+-]?\d+(?:(?:\.\d*)?(?:[eE][+-]?\d+)?)?\b/, "number"],

        // Identifiers and keywords
        [
          /[a-zA-Z_]\w*/,
          {
            cases: {
              "@keywords": "keyword",
              "@builtinFunctions": "keyword.function",
              "@builtinConstants": "constant.language",
              "@default": "identifier",
            },
          },
        ],

        // Operators
        [
          /@symbols/,
          {
            cases: {
              "@operators": "operator",
              "@default": "",
            },
          },
        ],

        // Brackets
        [/[()]/, "@brackets"],

        // Whitespace
        [/\s+/, "white"],
      ],

      comment: [
        [/[^\/*]+/, "comment"],
        [/\*\//, "comment", "@pop"],
        [/[\/*]/, "comment"],
      ],

      doubleString: [
        [/[^\\"]+/, "string"],
        [/\\./, "string.escape"],
        [/"/, "string", "@pop"],
      ],

      singleString: [
        [/[^\\']+/, "string"],
        [/\\./, "string.escape"],
        [/'/, "string", "@pop"],
      ],
    },
  });

  monaco.languages.setLanguageConfiguration(CQL_LANGUAGE_ID, {
    comments: {
      lineComment: "//",
      blockComment: ["/*", "*/"],
    },
    brackets: [
      ["{", "}"],
      ["[", "]"],
      ["(", ")"],
    ],
    autoClosingPairs: [
      { open: "{", close: "}" },
      { open: "[", close: "]" },
      { open: "(", close: ")" },
      { open: '"', close: '"' },
      { open: "'", close: "'" },
      { open: "/*", close: " */" },
    ],
    surroundingPairs: [
      { open: "{", close: "}" },
      { open: "[", close: "]" },
      { open: "(", close: ")" },
      { open: '"', close: '"' },
      { open: "'", close: "'" },
    ],
    folding: {
      markers: {
        start: /^\s*\/\*/,
        end: /^\s*\*\//,
      },
    },
  });
}

export function defineCqlTheme(monaco: typeof monacoTypes) {
  monaco.editor.defineTheme("cql-monokai", {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "keyword", foreground: "fb4b8c", fontStyle: "bold" },
      { token: "keyword.function", foreground: "66d9ef" },
      { token: "constant.language", foreground: "ae81ff" },
      { token: "comment", foreground: "75715e", fontStyle: "italic" },
      { token: "string", foreground: "e6db74" },
      { token: "number", foreground: "ae81ff" },
      { token: "operator", foreground: "f92672" },
      { token: "identifier", foreground: "f8f8f2" },
    ],
    colors: {
      "editor.background": "#272822",
      "editor.foreground": "#f8f8f2",
      "editorCursor.foreground": "#f8f8f0",
      "editor.lineHighlightBackground": "#3e3d32",
      "editor.selectionBackground": "#49483e",
      "editorLineNumber.foreground": "#90908a",
    },
  });
}
